name: projeto-final-bikes

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: projeto-final-jupyter
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "8890:8888"
      - "8501:8501"
    volumes:
      - .:/home/jovyan/work
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: projeto-final-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
